# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  mapErrorsToJson: true
  docEndpoints:
    raw: /api/v1/json
    ui : /api/v1/

# any other values in this file are just loaded into the config for application access...
