swagger: "2.0"
info:
  version: "0.0.1"
  title: Fixalicious

schemes:
  # tip: remove http to make production-grade
  - http
  - https
  
# format of the responses to the client (Accepts)
consumes:
  - application/json
produces:
  - application/json
paths:
  /session:
    x-swagger-router-controller: session
    get:
      summary: Get all sessions
      operationId: getAllSessions
      tags : [Session]
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/SessionResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /session/{name}:
    x-swagger-router-controller: session
    post:
      summary: Create a session
      operationId: postSession
      tags : [Session]
      parameters:
        - name: name
          in: path
          description: Name of the session
          required: true
          type: string
      responses:
        "200":
          description: Success   
    delete:
      summary: Delete a session
      operationId: deleteSession
      tags : [Session]
      parameters:
        - name: name
          in: path
          description: Name of the session
          required: true
          type: string
      responses:
        "200":
          description: Success
  /session/{name}/scenario:
    x-swagger-router-controller: session
    post:
      summary: Enable/disable scenarios for this session
      operationId: enableScenarios
      tags : [Session]
      parameters:
        - name: name
          in: path
          description: Name of the session
          required: true
          type: string     
        - name: changes
          in: body
          description: lists of scenarios to enable and disable
          required: true
          schema:
            $ref: "#/definitions/SessionScenarioChangeResource"
      responses:
        "200":
          description: Success   
  /transaction/{session}:
    x-swagger-router-controller: transaction
    get:
      summary: Get all transactions
      operationId: getAllTransactions
      tags : [Transaction]
      parameters:
        - name: session
          in: path
          description: FIX session name
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/TransactionResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Create a new transaction
      operationId: createTransaction
      tags : [Transaction]
      parameters:
        - name: session
          in: path
          description: FIX session name 
          required: true
          type: string
        - name: transaction
          in: body
          description: JSON object containing transaction details
          required: true
          schema:
            $ref: "#/definitions/TransactionResource"
      responses:
        "200":
          description: Success  
    delete:
      summary: Delete all transactions in a given session
      operationId: deleteTransaction
      tags : [Transaction]
      parameters:
        - name: session
          in: path
          description: FIX session name 
          required: true
          type: string
      responses:
        "200":
          description: Success            
  /template:
    x-swagger-router-controller: template
    get:
      summary: Get all FIX message templates
      operationId: getAllTemplates
      tags : [Template]
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/TemplateResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /template/{label}:
    x-swagger-router-controller: template
    post:
      summary: Create a new FIX message template
      operationId: createTemplate
      tags : [Template]
      parameters:
        - name: label
          in: path
          description: FIX session name 
          required: true
          type: string
        - name: template
          in: body
          description: array of keys and formulas
          required: true
          schema:
            $ref: "#/definitions/TemplateResource"
      responses:
        "200":
          description: Success
    delete:
      summary: Delete a template
      operationId: deleteTemplate
      tags : [Template]
      parameters:
        - name: label
          in: path
          description: Name of the template
          required: true
          type: string
      responses:
        "200":
          description: Success
  /scenario:
    x-swagger-router-controller: scenario
    get:
      summary: Get all Scenario
      operationId: getAll
      tags : [Scenario]
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/ScenarioResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /scenario/{label}:
    x-swagger-router-controller: scenario
    post:
      summary: Create a new scenario to run on incoming FIX messages
      operationId: create
      tags : [Scenario]
      parameters:
        - name: label
          in: path
          description: scenario label
          required: true
          type: string
        - name: scenario
          in: body
          description: code to execute when scenario is active
          required: true
          schema:
            $ref: "#/definitions/ScenarioResource"
      responses:
        "200":
          description: Success
    delete:
      summary: Delete a scenario
      operationId: delete
      tags : [Scenario]
      parameters:
        - name: label
          in: path
          description: Name of the session
          required: true
          type: string
      responses:
        "200":
          description: Success
# complex objects have schema definitions
definitions:
  ErrorResponse:
    description: Login result
  SessionResource:
    description: Session
    properties:
      name:
        type: string
  TransactionResource:
    description: Transaction
    properties:
      id:
        type: string
      direction:
        type: string
      message:
        type: string
  TemplateItemResource:
    description: Template Item a key value pair of FIX keys and formulas
    properties:
      key:
        type: string
      formula:
        type: string
  TemplateResource:
    description: Template
    properties:
      label: 
        type: string
      pairs:
        type: array
        items: 
          $ref: "#/definitions/TemplateItemResource"
  ScenarioResource:
    description: Scenario
    properties:
      label:
        type: string
      code:
        type: string
  SessionScenarioChangeResource:
    description: Scenarios to enable and disable on a session
    properties:
      enable:
        type: array
        items:
          type: string
      disable:
        type: array
        items:
          type: string