swagger: "2.0"
info:
  version: "0.0.1"
  title: Fixalicious

schemes:
  # tip: remove http to make production-grade
  - http
  - https
  
# format of the responses to the client (Accepts)
consumes:
  - application/json
produces:
  - application/json
paths:
  /session:
    x-swagger-router-controller: session
    get:
      summary: Get all sessions
      operationId: getAllSessions
      tags : [Session]
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/SessionResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /session/{name}/fake:
    x-swagger-router-controller: session
    post:
      summary: Create a session
      operationId: fakeIncoming
      tags : [Session]
      parameters:
        - name: name
          in: path
          description: Name of the session
          required: true
          type: string
      responses:
        "200":
          description: Success
  /transaction/{session}:
    x-swagger-router-controller: transaction
    get:
      summary: Get all transactions
      operationId: getAllTransactions
      tags : [Transaction]
      parameters:
        - name: session
          in: path
          description: FIX session name
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/TransactionResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Create a new transaction
      operationId: createTransaction
      tags : [Transaction]
      parameters:
        - name: session
          in: path
          description: FIX session name 
          required: true
          type: string
        - name: transaction
          in: body
          description: JSON object containing transaction details
          required: true
          schema:
            $ref: "#/definitions/TransactionResource"
      responses:
        "200":
          description: Success  
    delete:
      summary: Delete all transactions in a given session
      operationId: deleteTransaction
      tags : [Transaction]
      parameters:
        - name: session
          in: path
          description: FIX session name 
          required: true
          type: string
      responses:
        "200":
          description: Success            
  /action:
    x-swagger-router-controller: action
    get:
      summary: Get all FIX message actions
      operationId: getAllActions
      tags : [Action]
      responses:
        "200":
          description: Success
          schema:
            type: array
            items: 
              $ref: "#/definitions/ActionResource"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /action/{label}:
    x-swagger-router-controller: action
    post:
      summary: Create a new FIX message action
      operationId: createAction
      tags : [Action]
      parameters:
        - name: label
          in: path
          description: FIX session name 
          required: true
          type: string
        - name: action
          in: body
          description: array of keys and formulas
          required: true
          schema:
            $ref: "#/definitions/ActionResource"
      responses:
        "200":
          description: Success
    delete:
      summary: Delete an action
      operationId: deleteAction
      tags : [Action]
      parameters:
        - name: label
          in: path
          description: Name of the action
          required: true
          type: string
      responses:
        "200":
          description: Success
  /action/run/{label}:
    x-swagger-router-controller: action
    post:
      summary: Run a scenario against a provided FIX messages
      operationId: run
      tags : [Action]
      parameters:
        - name: label
          in: path
          description: scenario label
          required: true
          type: string
        - name: fixIn
          in: body
          description: Fix Message
          required: true
          schema: 
            "$ref": "#/definitions/AnyObject"
      responses:
        "200":
          description: Success
# complex objects have schema definitions
definitions:
  ErrorResponse:
    description: Login result
  SessionResource:
    description: Session
    properties:
      name:
        type: string
  TransactionResource:
    description: Transaction
    properties:
      id:
        type: string
      direction:
        type: string
      message:
        type: string
  ActionItemResource:
    description: Action Item a key value pair of FIX keys and formulas
    properties:
      key:
        type: string
      formula:
        type: string
  ActionResource:
    description: Action
    properties:
      label: 
        type: string
      pairs:
        type: array
        items: 
          $ref: "#/definitions/ActionItemResource"
  AnyObject:
    type: object